### ISSUE TITLE
sizeOf may only be used on fixed-size objects.

### ISSUE THREAD

**Issue by franck44** [ConsenSys/eth2.0-dafny#1]
Using sizeOf on variable-sized objects should be avoided.

https://github.com/PegaSysEng/eth2.0-dafny/blob/acb7b2c86731193bd0969b9c4b1bc24b493fdd19/src/dafny/ssz/Merkleise.dfy#L31

Later we may refine the Serialisable type into FixedSizeSer and VarSizeSer and use FixedSizeSer for the type of the parameter of SizeOf.

**Comment by booleanfunction** [comment]
type constraints included:

https://github.com/PegaSysEng/eth2.0-dafny/blob/93698db8f2a10bd5f4efd7abed2ea85f24542e35/src/dafny/ssz/Serialise.dfy#L45-L46
