### ISSUE TITLE
Please review commit for the xor function and related helpers

### ISSUE THREAD

**Issue by saltiniroberto** [ConsenSys/eth2.0-dafny#14]
Ref commit is dd3a5b972835a9445eb11bb8cd7f6ec6f7ada5bf

**Comment by saltiniroberto** [comment]
Ref commit is dd3a5b972835a9445eb11bb8cd7f6ec6f7ada5bf

**Comment by saltiniroberto** [comment]
Note the the function `uint8xor` has been renamed to `byteXor` and moved to `Eth2Types.dfy` in commit 155979b5681ba8a6eb07ded0e496458ea14926f7

**Comment by franck44** [comment]
These functions are not used.
