### ISSUE TITLE
Serialiased output type 

### ISSUE THREAD

**Issue by franck44** [ConsenSys/eth2.0-dafny#2]
https://github.com/PegaSysEng/eth2.0-dafny/blob/acb7b2c86731193bd0969b9c4b1bc24b493fdd19/src/dafny/ssz/Merkleise.dfy#L58

 type Bytes = seq<Byte> // i.e. the output of serialisation
    //type serialisedElement = seq<Byte> // i.e. the output of serialisation
    // bounds? should be at least 1 byte (if representing serialised output)
    // maybe call serialisedBytes or serialisedElement?

**Comment by booleanfunction** [comment]
`type Bytes` previously defined in Merkelise.dfy moved to Eth2Types.dfy and changed to begin with lowercase b to be consistent with its use in the Beacon chain. 

https://github.com/PegaSysEng/eth2.0-dafny/blob/93698db8f2a10bd5f4efd7abed2ea85f24542e35/src/dafny/utils/Eth2Types.dfy#L32-L33

**Comment by franck44** [comment]
This has been fixed long ago, so closing.
