### ISSUE TITLE
Investigate: new info Auto-accumulator tail-recursive using Dafny 3 

### ISSUE THREAD

**Issue by franck44** [ConsenSys/eth2.0-dafny#49]
Using Dafny 3.0.0, a (new?) info has showed up:
"Auto-accumulator tail-recursive".
This is not an error or warning but may deserve some attention: how do we suppress this info from showing up, like induction info?

And example is the tail recursive function `timeSeq` in `utils/Helpers.dfy`:
```dafny
 function method {:tailrecursion true} timeSeq<T>(t : T, k : nat) : seq<T> 
        ensures |timeSeq(t,k)| == k
        ensures forall i :: 0 <= i < k ==> timeSeq(t,k)[i] == t
        decreases k
    {
        if k == 0 then []
        else [t] + timeSeq(t, k - 1)
    }
```
Even with `{:tailrecursion true}` attribute the info appears using Dafny 3.

**Comment by keyboardDrummer** [comment]
This seems to be a duplicate of https://github.com/dafny-lang/dafny/pull/1415#issuecomment-918237133 which should be resolved in the upcoming Dafny release.

**Comment by franck44** [comment]
@keyboardDrummer Thanks a lot for the update. Looking forward to the new release!

**Comment by franck44** [comment]
Will be fixed in next Dafny release so closing this issue.
