### ISSUE TITLE
Collect stats

### ISSUE THREAD

**Issue by franck44** [ConsenSys/eth2.0-dafny#7]
Design scripts to collect statistics about Dafny files.

- number of lines of code (started in count_lines.py)
- call graph (call_graph.py)

**Comment by booleanfunction** [comment]
[Python notebook](https://github.com/PegaSysEng/eth2.0-dafny/blob/master/scripts/getStats.ipynb) created to automate the process of collecting stats relating to the Dafny files.

This notebook is a first cut and is not efficient. It should also be converted to a python script once finalised.

**Comment by franck44** [comment]
The scripts (script folder) have been updated. It is also possible to generate a call graph using Dafny call graph features.
